apiVersion: v1
kind: Secret
metadata:
  name: github
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/wuerzelchen/project-deployment-dev
---
apiVersion: v1
kind: Secret
metadata:
  name: helm
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  name: helm-oci
  url: wkshp3efn4.azurecr.io
  enableOCI: "true"
  username: wkshp3efn4
  password: 38nRj0CNGa/YMF9b7KEKTyh5JOqV9NNOl0ULnYHlW/+ACRD+dwfe
